# Generated by Django 3.1.3 on 2020-12-14 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(max_length=50)),
                ('ou', models.CharField(max_length=255)),
                ('dc', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('profile', models.CharField(max_length=255)),
                ('homedir', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.CharField(max_length=255)),
                ('profilePassword', models.CharField(max_length=255)),
                ('profileEnablePassword', models.CharField(max_length=255)),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('managementIP', models.GenericIPAddressField()),
                ('localPort', models.CharField(max_length=255)),
                ('remotePort', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('softwareVersion', models.CharField(max_length=255)),
                ('deviceType', models.CharField(default='cisco_ios', max_length=255)),
                ('capabilities', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('managementIP', models.GenericIPAddressField()),
                ('localPort', models.CharField(max_length=255)),
                ('remotePort', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('softwareVersion', models.CharField(max_length=255)),
                ('deviceType', models.CharField(default='cisco_ios', max_length=255)),
                ('capabilities', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
