# Generated by Django 3.1.3 on 2021-01-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='managementIP',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='devicetemp',
            name='managementIP',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
