# Generated by Django 3.2.1 on 2021-05-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_userconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='fileName',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
