# Generated by Django 3.2.1 on 2021-05-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_userconfig_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='dateAdded',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
