# Generated by Django 3.2.1 on 2021-05-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_userconfig_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
