# Generated by Django 3.2.1 on 2021-06-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_nagiosserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interfaceName', models.CharField(max_length=255)),
                ('keepAlive', models.BooleanField(default=False)),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.device')),
            ],
        ),
    ]
