# Generated by Django 3.2.1 on 2021-07-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_deviceinterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='monitored',
            field=models.BooleanField(default=False),
        ),
    ]
